---
title: "Workshop 1"
author: "Melissa Arévalo y Pablo Uribe"
date: "2024-03-08"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tinytex)
library(reticulate)
library(knitr)
```

```{python, include=FALSE}
import pandas as pd

df = pd.read_csv(r"C:\Users\DO IT WISER\Documents\Personal\Monografía\Procesamiento R\processed_data.csv")

df_r = df.head()
print(df_r)
```

## Datos Estandarizados

```{r, echo=FALSE, include=TRUE, eval=TRUE}

library(knitr)
library(kableExtra)

aux = py$df_r

kable(aux, digits = 3) %>%
  kable_styling(full_width = FALSE)
```

```{python}

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import norm


def values_density (columna):
  x_values = np.linspace(columna.mean() - 3 * columna.std(), columna.mean() + 3 * columna.std(), 100)
  pdf = norm.pdf(x_values, columna.mean(), columna.std())
  
  return x_values,pdf

x_values_ndvi, pdf_ndvi = values_density(df['NDVI'])
x_values_precipitacion, pdf_precipitacion = values_density(df['Precipitación'])

fig, axs = plt.subplots(1, 2, figsize=(8, 4))

sns.histplot(df['NDVI'], bins=12, color='darkseagreen', ax=axs[0], edgecolor='black', alpha=0.7)
axs[0].plot(x_values_ndvi, pdf_ndvi, 'k-', lw=2, label='Ajuste Normal')
axs[0].set_title('NDVI')
axs[0].legend() 

sns.histplot(df['Precipitación'], bins=20, color='darkseagreen', ax=axs[1], edgecolor='black', alpha=0.7)
axs[1].plot(x_values_precipitacion, pdf_precipitacion, 'k-', lw=2, label='Ajuste Normal')
axs[1].set_title('Precipitación')
axs[1].legend()  

plt.tight_layout(w_pad=2)

plt.show()

```

```{python}
x_values_inter, pdf_inter = values_density(df['Intercepción'])
x_values_evap, pdf_evap = values_density(df['Evapotranspiración'])

fig, axs = plt.subplots(1, 2, figsize=(8, 4))

sns.histplot(df['Intercepción'], bins=12, color='darkseagreen', ax=axs[0], edgecolor='black', alpha=0.7)
axs[0].plot(x_values_inter, pdf_inter, 'k-', lw=2, label='Ajuste Normal')
axs[0].set_title('Intercepción')
axs[0].legend() 

sns.histplot(df['Evapotranspiración'], bins=20, color='darkseagreen', ax=axs[1], edgecolor='black', alpha=0.7)
axs[1].plot(x_values_evap, pdf_evap, 'k-', lw=2, label='Ajuste Normal')
axs[1].set_title('Evapotranspiración')
axs[1].legend()  

plt.tight_layout(w_pad=2)

plt.show()

```

```{python}
x_values_evapP, pdf_evapP = values_density(df['Evapotranspiración_Potencial'])
x_values_Hum, pdf_Hum = values_density(df['Humedad_Suelo'])

fig, axs = plt.subplots(1, 2, figsize=(8, 4))

sns.histplot(df['Evapotranspiración_Potencial'], bins=12, color='darkseagreen', ax=axs[0], edgecolor='black', alpha=0.7)
axs[0].plot(x_values_evapP, pdf_evapP, 'k-', lw=2, label='Ajuste Normal')
axs[0].set_title('Evapotranspiración_Potencial')
axs[0].legend() 

sns.histplot(df['Humedad_Suelo'], bins=20, color='darkseagreen', ax=axs[1], edgecolor='black', alpha=0.7)
axs[1].plot(x_values_Hum, pdf_Hum, 'k-', lw=2, label='Ajuste Normal')
axs[1].set_title('Humedad_Suelo')
axs[1].legend()  

plt.tight_layout(w_pad=2)

plt.show()

```
